services:
  - type: web
    name: naijabuzz-live
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    # ← delete the DATABASE_URL line here

  - type: cron
    name: naijabuzz-updater
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python generator.py
    schedule: "0 */4 * * *"
    # ← delete the DATABASE_URL line here too
