services:
  - type: web
    name: naijabuzz-live
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn main:app
